In [5]:
import pandas as pd

In [6]:
df=pd.read_csv(r'C:\MyFILES\DV-project\Zomato\address_zomato.csv')

#### Geocoding

In [7]:
df

,address,name,rate,votes,location
0,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,4.1,775,Banashankari
1,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,4.1,787,Banashankari
2,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,3.8,918,Banashankari
3,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,3.7,88,Banashankari
4,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,3.8,166,Basavanagudi
...,...,...,...,...,...
9494,"Unit 04-01, 4th floor, Ascendas Park Square Ma...",Chung Wah,2.5,73,"ITPL Main Road, Whitefield"
9495,"107/PA, ITPL Main Road, Whitefield, Bangalore",Nawabs Empire,3.2,5,"ITPL Main Road, Whitefield"
9496,"Cessna Business Park, Sarjapur ÃÂÃÂÃÂÃÂ...",Nook - Aloft Bengaluru Cessna Business Park,4.2,411,Bellandur
9497,"44, Kodigehalli to Hoodi Main Road, Mahadevapu...",SeeYa Restaurant,3.3,4,KR Puram
9498,"139/C1, Next To GR Tech Park, Pattandur Agraha...",Bhagini,2.5,81,Whitefield

In [8]:
from geopy.geocoders import Nominatim
geolocator= Nominatim(user_agent = 'nkrdharmendra@gmail.com')

location =geolocator.geocode()

TypeError: Nominatim.geocode() missing 1 required positional argument: 'query'